# Generated by Django 2.1.1 on 2018-09-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Title', models.CharField(max_length=50)),
                ('Url', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=100)),
                ('Detail', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'News',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SystemLog',
                'managed': True,
            },
        ),
    ]
